site:
  title: Boost.Multi
  start_page: multi::index.adoc
content:
  sources:
    - url: ..
      start_path: doc
      branches: HEAD
output:
  dir: html
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
  output_dir: multi/_
  supplemental_files: ./supplemental-ui
antora:
  extensions:
    - '@antora/lunr-extension'
